import time

def sphinx():
    print()

    print("                               /\=""^^^^^^∧ ")
    time.sleep(0.1)
    print("                   /\       , /  \_\_|_/_)")
    time.sleep(0.1)
    print("                  /';;     /| \\\/.-. .-. /")
    time.sleep(0.1)
    print("                 / \;|    /. \,S'  -   - |")
    time.sleep(0.1)
    print("                / -.;|    | '.SS     _|  ;")
    time.sleep(0.1)
    print("               ; '-.;\,   |'-.SS\   __  /S")
    time.sleep(0.1)
    print("               | _  ';\\.   \\' SSS\_____/SS")
    time.sleep(0.1)
    print("               |  '- ';\\.   \_SSS[_____]SS")
    time.sleep(0.1)
    print("               \ '--.-';;-. __SSS/\    SSS")
    time.sleep(0.1)
    print("                \  .--' ';;'.=SSS`\\_\_SSS")
    time.sleep(0.1)
    print("                 `._ .-` _ ;;..=.=.=.\.=\ ")
    time.sleep(0.1)
    print("                    ;-._-'  _.;\.=.=.=.|.=|")
    time.sleep(0.1)
    print("          ,     _.-'    ''=._  ;\=.=__/__/")
    time.sleep(0.1)
    print("          )\ .'`   __        ''.;|.=.=.=./")
    time.sleep(0.1)
    print("          (_\   .-`  '.   |    \/=.=.=/`")
    time.sleep(0.1)
    print("           /\\         \-,|     |.--'|")
    time.sleep(0.1)
    print("          /  \`,       //  \    | |  |")
    time.sleep(0.1)
    print("         ( (__) )  _.-'--,  \   | |  '--,")
    time.sleep(0.1)
    print("          ;----' -'--,__}}}  \  '--, __}}}")
    time.sleep(0.1)
    print("          \_________}}}       \___}}}")
    print()
    print()


